import time
import turtle


def display_one():  # Display 1 on the screen
    turtle.forward(100)


def display_two():  # Display 2 on the screen
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)


def display_three():  # Display 3 on the screen
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)


def display_four():  # Display 4 on the screen
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.left(90)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(50)


def display_five():  # Display 5 on the screen
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)


def display_six():  # Display 6 on the screen
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)


def display_seven():  # Display 7 on the screen
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)
    

def display_eight():  # Display 8 on the screen
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)


def display_nine():  # Display 9 on the screen
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)


def display_zero():  # Display 0 on the screen
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.penup()
    turtle.forward(50)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)


def testing():  # Testing function
    turtle.left(90)
    display_one()
    time.sleep(1)
    turtle.home()
    turtle.reset()
    turtle.clear()
    time.sleep(3)
    turtle.left(90)
    display_two()
    turtle.clear()
    turtle.home()
    turtle.reset()
    turtle.left(90)
    display_three()
    turtle.clear()
    turtle.home()
    turtle.reset()
    turtle.left(90)
    display_four()
    turtle.clear()
    turtle.home()
    turtle.reset()
    turtle.left(90)
    display_five()
    turtle.clear()
    turtle.home()
    turtle.reset()
    turtle.left(90)
    display_six()
    turtle.clear()
    turtle.home()
    turtle.reset()
    turtle.left(90)
    display_seven()
    turtle.clear()
    turtle.home()
    turtle.reset()
    turtle.left(90)
    display_eight()
    turtle.clear()
    turtle.home()
    turtle.reset()
    turtle.left(90)
    display_nine()
    turtle.clear()
    turtle.home()
    turtle.reset()
    turtle.left(90)
    display_zero()